"""LaTeX output.

The board is drawn by the ``chessboard`` package, which takes a FEN directly --
the canonical way to set a chess diagram in LaTeX, and the reason this export
does not try to reuse the chess fonts the other formats embed. The generated
file compiles with pdflatex; it needs TeX Live's *games* collection (or MiKTeX's
``chessboard`` package) installed.

Everything that varies per diagram is written with ``setfen`` alone, which is
the one key of that package this module depends on for every position. Board
size, coordinate labels and anything else stylistic is set once, in a single
``\\setchessboard`` line in the preamble, so a document can be restyled -- or
repaired against a different package version -- by editing one line.
"""

from __future__ import annotations

import re
from pathlib import Path

from .. import __version__
from ..fen import board_is_flipped, parse_fen
from ..fonts import resolve_board_font
from ..i18n import _answers_heading, _lichess_label, tr
from ..layouts import LAYOUTS
from ..model import PositionDict
from ..options import RenderOptions
from ..parsers import _clean_moves
from .common import (
    _anchor_id,
    _chapter_groups,
    _format_number,
    _layout_columns,
    _lichess_analysis_url,
    _make_title,
    _numbering,
    _split_title_number_prefix,
)

# The ten characters TeX reads as markup, and what to write instead.
_TEX_REPLACEMENTS = {
    '\\': r'\textbackslash{}',
    '{': r'\{',
    '}': r'\}',
    '#': r'\#',
    '$': r'\$',
    '%': r'\%',
    '&': r'\&',
    '_': r'\_',
    '~': r'\textasciitilde{}',
    '^': r'\textasciicircum{}',
}
_TEX_RE = re.compile('|'.join(re.escape(ch) for ch in _TEX_REPLACEMENTS))

# Paper sizes the geometry package knows by name.
_GEOMETRY_PAPER = {
    'a3': 'a3paper', 'a4': 'a4paper', 'a5': 'a5paper',
    'letter': 'letterpaper', 'legal': 'legalpaper',
}

# babel's name for each language this program speaks. babel also pulls in the
# right font encoding, which is what makes Cyrillic typeset at all under
# pdflatex -- T1 alone cannot represent it, and the sample games are Russian.
_BABEL_LANGUAGES = {
    'en': 'english', 'ru': 'russian', 'pt': 'portuguese', 'es': 'spanish',
}

_CYRILLIC_RE = re.compile(r'[Ѐ-ӿ]')


def _document_uses_cyrillic(positions: list[PositionDict], opts: RenderOptions) -> bool:
    """True when anything that will be typeset carries Cyrillic.

    This decides which font encoding ends up the default one, and getting it
    wrong is not cosmetic: pdflatex stops on the first Cyrillic letter with
    "Command \\CYRR unavailable in encoding T1" and writes no PDF at all.

    Everything that can reach the page is examined -- the positions, every text
    option, and the labels this program writes itself, which are Cyrillic when
    the language is Russian.
    """
    texts = [str(position.get(key, '') or '')
             for position in positions
             for key in ('comment', 'event', 'white', 'black', 'date', 'chapter', 'moves')]
    texts += [value for value in opts.to_dict().values() if isinstance(value, str)]
    texts += [_answers_heading(opts), _lichess_label(opts), tr('contents', opts.lang)]
    return any(_CYRILLIC_RE.search(text) for text in texts)


def _escape(text: str) -> str:
    """Escape TeX markup in text that came from the input file."""
    return _TEX_RE.sub(lambda m: _TEX_REPLACEMENTS[m.group()], str(text or ''))


def _escape_url(url: str) -> str:
    """Escape the two characters that still bite inside \\href."""
    return str(url or '').replace('\\', r'\\').replace('%', r'\%').replace('#', r'\#')


def _running_text(template: str, opts: RenderOptions) -> str:
    """Expand {page}, {total} and {chapter} into LaTeX for a running head."""
    text = _escape(template)
    # Escaping turned the braces into \{ \}, so the placeholders are matched back.
    text = text.replace(r'\{page\}', r'\thepage')
    text = text.replace(r'\{total\}', r'\pageref{LastPage}')
    text = text.replace(r'\{chapter\}', r'\leftmark')
    return text


def _board_font_size(opts: RenderOptions) -> int:
    """Return the board size in points, from --font-size or the layout."""
    return opts.font_size if opts.font_size > 0 else LAYOUTS[opts.layout_idx][6]


def _preamble(opts: RenderOptions, cyrillic: bool = False) -> list[str]:
    """Return everything before \\begin{document}."""
    page = opts.page
    paper = _GEOMETRY_PAPER.get(opts.page_size, 'a4paper')
    geometry = [paper, f'left={page.margin_lr}mm', f'right={page.margin_lr}mm',
                f'top={page.margin_tb}mm', f'bottom={page.margin_tb}mm']
    if opts.landscape:
        geometry.append('landscape')

    lines = [
        f'% Generated by DiagPDF {__version__}.',
        '%',
        '% Compile with pdflatex (twice, so the contents and {total} settle):',
        '%     pdflatex document.tex && pdflatex document.tex',
        '%',
        '% Needs the chessboard package - TeX Live collection-games, or the',
        '% MiKTeX package of the same name.',
        r'\documentclass[10pt]{article}',
        # The encoding listed *last* is the one in force, and only one of the
        # two can be. T1 is the better default for Latin -- accented letters are
        # single glyphs, so they hyphenate -- but it has no Cyrillic at all, and
        # a document carrying any stops the compiler dead. So the document
        # decides: T2A goes last exactly when there is Cyrillic to typeset.
        r'\usepackage[T1,T2A]{fontenc}' if cyrillic else r'\usepackage[T2A,T1]{fontenc}',
        r'\usepackage[utf8]{inputenc}',
        f'\\usepackage[{_BABEL_LANGUAGES.get(opts.lang, "english")}]{{babel}}',
        f'\\usepackage[{",".join(geometry)}]{{geometry}}',
        r'\usepackage{chessboard}',
        r'\usepackage{multicol}',
        r'\usepackage{fancyhdr}',
        r'\usepackage{lastpage}',
        r'\usepackage[hidelinks]{hyperref}',
        '',
        '% Every stylistic choice about the board lives on this one line.',
        f'\\setchessboard{{boardfontsize={_board_font_size(opts)}pt,'
        f'label={"true" if opts.coords else "false"}}}',
        '',
    ]

    # Loaded only when one is asked for, so an ordinary document does not
    # acquire a package requirement it never uses.
    if opts.watermark.strip():
        lines += [
            r'\usepackage{draftwatermark}',
            f'\\SetWatermarkText{{{_escape(opts.watermark.strip())}}}',
            r'\SetWatermarkScale{4}',
            # The package measures the mark by lightness, where 1 is invisible.
            f'\\SetWatermarkLightness{{{1 - opts.watermark_opacity / 100:.2f}}}',
            '',
        ]

    metadata = [
        ('pdftitle', opts.doc_title.strip()),
        ('pdfauthor', opts.doc_author.strip()),
        ('pdfsubject', opts.doc_subject.strip()),
        ('pdfkeywords', opts.doc_keywords.strip()),
    ]
    filled = [f'{key}={{{_escape(value)}}}' for key, value in metadata if value]
    if filled:
        lines += [f'\\hypersetup{{{",".join(filled)}}}', '']

    header, footer = opts.header_text, opts.footer_text
    if header or footer:
        lines += [r'\pagestyle{fancy}', r'\fancyhf{}', r'\renewcommand{\headrulewidth}{0pt}']
        if header:
            lines.append(f'\\fancyhead[C]{{{_running_text(header, opts)}}}')
        if footer:
            lines.append(f'\\fancyfoot[C]{{{_running_text(footer, opts)}}}')
        lines.append('')
    else:
        lines += [r'\pagestyle{empty}', '']
    return lines


def _cover(opts: RenderOptions) -> list[str]:
    """Return a title page."""
    title = _escape((opts.cover_title or opts.doc_title).strip())
    subtitle = _escape(opts.cover_subtitle.strip())
    author = _escape((opts.cover_author or opts.doc_author).strip())
    out = [r'\begin{titlepage}', r'\centering', r'\vspace*{0.3\textheight}']
    if title:
        out.append(f'{{\\Huge\\bfseries {title}\\par}}')
    if subtitle:
        out += [r'\vspace{1em}', f'{{\\Large {subtitle}\\par}}']
    if author:
        out += [r'\vfill', f'{{\\large {author}\\par}}']
    out += [r'\end{titlepage}', '']
    return out


def _diagram(position: PositionDict, number: int, opts: RenderOptions,
             column_width: str, anchor: int) -> list[str]:
    """Return one diagram as a minipage: title, board, notation lines, link."""
    fen = str(position.get('fen', '') or '').strip()
    title = _make_title(position, number, opts.title_template,
                        opts.title_mode, opts.title_custom, opts)
    prefix, rest = _split_title_number_prefix(title, number, opts)

    shown = _escape(title)
    if opts.answers_section and prefix:
        shown = (f'\\hyperlink{{answer-{anchor}}}{{{_escape(prefix.strip())}}}'
                 + (f' {_escape(rest)}' if rest else ''))

    out = [
        f'\\begin{{minipage}}[t]{{{column_width}}}',
        r'\centering',
        f'\\hypertarget{{diagram-{anchor}}}{{}}%',
        f'{{\\small\\bfseries {shown}\\par}}',
        r'\vspace{0.3em}',
    ]

    _, side = parse_fen(fen)
    # setfen is the only per-diagram key this depends on; inverse is written
    # only when the board really is seen from Black's side.
    keys = f'setfen={{{fen}}}'
    if board_is_flipped(side, opts.flip, opts.flip_auto):
        keys += ',inverse=true'
    out.append(f'\\chessboard[{keys}]')

    if opts.lines_count > 0:
        out.append(r'\vspace{0.4em}\par')
        for index in range(opts.lines_count):
            label = f'{index + 1}.~' if opts.lines_mode == 'numbered' else ''
            if opts.lines_mode == 'numbered' and index == 0 and side == 'b':
                label += r'\dots~'
            out.append(f'{{\\footnotesize {label}\\rule{{0.7\\linewidth}}{{0.4pt}}\\par}}')

    if opts.lichess_link:
        url = _lichess_analysis_url(fen)
        if url:
            out.append(f'\\par{{\\footnotesize\\href{{{_escape_url(url)}}}'
                       f'{{{_escape(_lichess_label(opts))}}}}}')

    if not opts.answers_section:
        moves = _clean_moves(str(position.get('moves', '') or ''))
        if moves:
            out.append(f'\\par{{\\footnotesize {_escape(moves)}\\par}}')

    out.append(r'\end{minipage}')
    return out


def generate_latex(positions: list[PositionDict], opts: RenderOptions | dict,
                   out_path, progress=None) -> None:
    """Write a LaTeX source document that typesets the diagrams."""
    opts = RenderOptions.coerce(opts)
    # The chessboard package draws the board from the FEN, so the chess font
    # plays no part here -- but a misspelled --font is still a mistake, and it
    # should be reported by every format alike.
    resolve_board_font(opts.font)
    valid = [p for p in positions if str(p.get('fen', '') or '').strip()]
    total = len(valid)

    columns = _layout_columns(opts)
    # Short of the full share: N boxes of exactly textwidth/N leave no room for
    # the glue between them and TeX reports an overfull line on every row. The
    # slack is taken up by the \hfill written between the boxes.
    column_width = f'{0.97 / columns:.4f}\\textwidth'

    parts: list[str] = _preamble(opts, _document_uses_cyrillic(valid, opts))
    parts.append(r'\begin{document}')
    if opts.cover:
        parts += _cover(opts)
    if opts.contents:
        heading = opts.contents_title.strip() or tr('contents', opts.lang)
        parts += [f'\\renewcommand{{\\contentsname}}{{{_escape(heading)}}}',
                  r'\tableofcontents', r'\clearpage', '']

    numbers = _numbering(valid, opts)
    answers: list[tuple[int, int, str]] = []

    def flush_answers() -> None:
        """Typeset the solutions gathered so far, then forget them."""
        if not answers:
            return
        parts.extend(['', r'\clearpage' if opts.answers_new_page else r'\bigskip',
                      f'\\section*{{{_escape(_answers_heading(opts))}}}', ''])
        # multicol refuses a single column, so it is only used when asked for two.
        if opts.answers_cols > 1:
            parts.append(f'\\begin{{multicols}}{{{opts.answers_cols}}}')
        for number, anchor, moves in answers:
            parts.append(
                f'\\noindent\\hypertarget{{answer-{anchor}}}{{}}'
                f'\\hyperlink{{diagram-{anchor}}}{{{_escape(_format_number(number, opts))}}}. '
                f'{_escape(moves)}\\par'
            )
        if opts.answers_cols > 1:
            parts.append(r'\end{multicols}')
        answers.clear()

    done = 0
    for group_index, (chapter, indices) in enumerate(_chapter_groups(valid)):
        if chapter:
            # A chapter starts a page of its own, as it does in every other
            # paginated format. \section does not break by itself -- in the
            # article class a section is meant to flow -- so the break is asked
            # for. Never before the first one: \clearpage on an empty page ships
            # nothing out, but the cover and the contents have already broken it.
            if group_index:
                parts.append(r'\clearpage')
            parts += ['', f'\\section{{{_escape(chapter)}}}', '']
        for column, index in enumerate(indices):
            position = valid[index]
            number = numbers[index]
            parts += _diagram(position, number, opts, column_width, _anchor_id(index))
            parts.append(r'\hfill' if (column + 1) % columns else r'\par\vspace{1.2em}')

            moves = _clean_moves(str(position.get('moves', '') or ''))
            if opts.answers_section and moves:
                answers.append((number, _anchor_id(index), moves))

            done += 1
            if progress and total:
                progress(int(done * 100 / total))
        parts.append(r'\par')

        if opts.answers_section and opts.answers_after_chapter:
            flush_answers()

    if opts.answers_section:
        flush_answers()

    parts += ['', r'\end{document}', '']
    if progress:
        progress(100)
    Path(out_path).write_text('\n'.join(parts), encoding='utf-8')
